// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dycgxsfxfhzpxchlbtef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5Y2d4c2Z4Zmh6cHhjaGxidGVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTc1MjUsImV4cCI6MjA2MTQzMzUyNX0.NedHPjvHE-Ds2jASb1PivIrE8hP9rHocISKpVSG9Ysg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);